language: cpp

jobs:
  include:
    - os: linux
      sudo: required
      services:
        - docker
    - os: osx
  
before_install:
  - curl -Ls -o Dockerfile-debian-stretch https://raw.githubusercontent.com/coslyk/docker-deb-builder/master/Dockerfile-debian-stretch
  - curl -Ls -o build https://github.com/coslyk/docker-deb-builder/raw/master/build
  - curl -Ls -o build-helper.sh https://github.com/coslyk/docker-deb-builder/raw/master/build-helper.sh
  - chmod +x build build-helper.sh

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt coslyk/mpv/mpv-lite ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker build -t docker-deb-builder:stretch -f Dockerfile-debian-stretch . ; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./build -i docker-deb-builder:stretch -o . . ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then /usr/local/opt/qt/bin/qmake; make; fi
