language: cpp

jobs:
  include:
    - os: linux
      sudo: required
      services:
        - docker
    - os: osx
  
before_install:
  - curl -Ls -o Dockerfile-debian-stretch https://raw.githubusercontent.com/coslyk/docker-deb-builder/master/Dockerfile-debian-stretch
  - curl -Ls -o build https://github.com/coslyk/docker-deb-builder/raw/master/build
  - curl -Ls -o build-helper.sh https://github.com/coslyk/docker-deb-builder/raw/master/build-helper.sh
  - chmod +x build build-helper.sh

install:
  - [ "$TRAVIS_OS_NAME" = "osx" ] && brew update
  - [ "$TRAVIS_OS_NAME" = "osx" ] && brew install coslyk/mpv/mpv-lite
  - [ "$TRAVIS_OS_NAME" = "linux" ] && docker build -t docker-deb-builder:stretch -f Dockerfile-debian-stretch .

script:
  - [ "$TRAVIS_OS_NAME" = "linux" ] && ./build -i docker-deb-builder:stretch -o . .
  - [ "$TRAVIS_OS_NAME" = "osx" ] && qmake
