language: cpp

jobs:
  include:
    - os: linux
      sudo: required
      services:
        - docker
    - os: osx
  
before_install:
  - curl -Ls -o Dockerfile-debian-stretch https://raw.githubusercontent.com/coslyk/docker-deb-builder/master/Dockerfile-debian-stretch
  - curl -Ls -o build https://github.com/coslyk/docker-deb-builder/raw/master/build
  - curl -Ls -o build-helper.sh https://github.com/coslyk/docker-deb-builder/raw/master/build-helper.sh
  - chmod +x build build-helper.sh

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt coslyk/mpv/mpv-lite ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker build -t docker-deb-builder:stretch -f Dockerfile-debian-stretch . ; fi
  
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir build; ./build -i docker-deb-builder:stretch -o build . ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then /usr/local/opt/qt/bin/qmake; make; fi

deploy:
  - provider: releases
    api_key:
      secure: D/oXrqI/M8RBR/GZU4io4rYo7PpLv5ixkX+HF9to8zxwbbdqySwFr11fQpNGrH0oISPziXqRWOVZpaKdyxCHh9OG5FSn1rCzBtUMiS6+LDGwX2l/rWcEr2TvBtKqQOML0pCCHZ4ZTfYDYvXpqib+hrSMeln2RfsdxS7iAc6JgoLwdArWo6+4r82VFwz4ON2BnorPg7o0p0QJO1WZVcte+JhmmqpgRyzg4Fal82MvCpEtmNM/X5he//OfQsijQ+jahKbHmZHIra6Hre+tyZpRUbQMVZJrg7S+POcge4e9pgm6Fxyy5BObeyjou523xhGitD66lwsw87Nmh3XUaFyGAfQ8lrxWr01JyiNmgBVzgWd+ZJIPUvkmlVtm+riE9BrP9TRq56nnjbWeA9oQJcQDBn8wMCo/ivEQt4lEJr1l7+fxqVvJqz7StMhBPV1pbSI9QKTgIBtDr/RuaWIgRQ9hYyD/+P8e7934rkB/bSYHEmzH7NKUmMRPbjzeO+WedKKaXOuJXLyHQcVY70KS+DWxmAgLUK7TEhgdGYYKlLuM8lFAHE0RbrYsPbsE6qalP8AeEevxdAlCpMThOzmnP3a9Hkni2PLn0E3YAHeN6GcJrfWrigdldLbCpwc54mJwOKuVWq1W1OFLsC3eXP1SHnh7IaGvJpSoDaogI4W+ldr96nw=
    file: build/*.deb
    file_glob: true
    on:
      repo: coslyk/moonplayer
      condition: "$TRAVIS_OS_NAME = linux "
